// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYpv2HN59u6FBvBTrV_N5Aywcnm3qloxw',
    appId: '1:422050369592:web:9c974963443f7f7c3a16cd',
    messagingSenderId: '422050369592',
    projectId: 'cn333-8e548',
    authDomain: 'cn333-8e548.firebaseapp.com',
    storageBucket: 'cn333-8e548.firebasestorage.app',
    measurementId: 'G-SMQPQWJSL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqwcwJI8JwlvyaMDrTkWepQ1Qw6Qf8AHY',
    appId: '1:422050369592:android:fc4e0b9ea7d38ea83a16cd',
    messagingSenderId: '422050369592',
    projectId: 'cn333-8e548',
    storageBucket: 'cn333-8e548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ur6DjL5u3NjBVtvMJkhSLzqfMe07k6s',
    appId: '1:422050369592:ios:19578aaeb49747673a16cd',
    messagingSenderId: '422050369592',
    projectId: 'cn333-8e548',
    storageBucket: 'cn333-8e548.firebasestorage.app',
    iosBundleId: 'com.example.ootdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ur6DjL5u3NjBVtvMJkhSLzqfMe07k6s',
    appId: '1:422050369592:ios:19578aaeb49747673a16cd',
    messagingSenderId: '422050369592',
    projectId: 'cn333-8e548',
    storageBucket: 'cn333-8e548.firebasestorage.app',
    iosBundleId: 'com.example.ootdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYpv2HN59u6FBvBTrV_N5Aywcnm3qloxw',
    appId: '1:422050369592:web:508c2e9a92b8ee5d3a16cd',
    messagingSenderId: '422050369592',
    projectId: 'cn333-8e548',
    authDomain: 'cn333-8e548.firebaseapp.com',
    storageBucket: 'cn333-8e548.firebasestorage.app',
    measurementId: 'G-0JYW4QV21M',
  );

}